server:
  port: ${port:8000}

# xxl.job.admin.addresses  xxl.job.executor.appname  xxl.job.executor.port
xxl:
  job:
    admin:
      addresses: http://192.168.11.100:8888/xxl-job-admin
    executor:
      appname: executor-test2
      port: ${executor.port:9999}

#spring:
#  profiles:
#    active: dev
#
#logging:
#  level:
#    com:
#      sky:
#        mapper: debug
#        service: info
#        controller: info
#
#sky:
#  alioss:
#    endpoint: ${sky.alioss.endpoint}
#    access-key-id: ${sky.alioss.access-key-id}
#    access-key-secret: ${sky.alioss.access-key-secret}
#    bucket-name: ${sky.alioss.bucket-name}

