server:
  port: 8000
spring:
  application:
    name: kafka-demo
  kafka:
    bootstrap-servers: 192.168.11.100:9092
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${spring.application.name}-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
# spring:
#   profiles:
#     active: dev

# logging:
#   level:
#     com:
#       sky:
#         mapper: debug
#         service: info
#         controller: info

# sky:
#   alioss:
#     endpoint: ${sky.alioss.endpoint}
#     access-key-id: ${sky.alioss.access-key-id}
#     access-key-secret: ${sky.alioss.access-key-secret}
#     bucket-name: ${sky.alioss.bucket-name}

