#server:
#  port: 8000
#
#spring:
#  profiles:
#    active: dev
#
#logging:
#  level:
#    com:
#      sky:
#        mapper: debug
#        service: info
#        controller: info
#
#sky:
#  alioss:
#    endpoint: ${sky.alioss.endpoint}
#    access-key-id: ${sky.alioss.access-key-id}
#    access-key-secret: ${sky.alioss.access-key-secret}
#    bucket-name: ${sky.alioss.bucket-name}
server:
  port: 8888
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_cache_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1111
  redis:
    host: localhost
    port: 6379
    password:
    database: 3


logging:
  level:
    com:
      spring_cache:
        mapper: debug
        service: info
        controller: info
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
