server:
  port: 8000
cartoon:
  cat:
    name: "图多盖洛"
    age: 5
  mouse:
    name: "泰菲"
    age: 1
# spring:
#   profiles:
#     active: dev

# logging:
#   level:
#     com:
#       sky:
#         mapper: debug
#         service: info
#         controller: info

# sky:
#   alioss:
#     endpoint: ${sky.alioss.endpoint}
#     access-key-id: ${sky.alioss.access-key-id}
#     access-key-secret: ${sky.alioss.access-key-secret}
#     bucket-name: ${sky.alioss.bucket-name}

